apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-slave-deployment
  labels:
    app: locust-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-slave
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      containers:
      - name: k8s-loadtest-slave
        image: ${DOCKER_IMAGE}
        imagePullPolicy: Always  
        env:
        - name: TRACKER_URL
          value: ${TRACKER_URL}
      imagePullSecrets:
      - name: regcred
